/bin/sh -c #(nop) MAINTAINER Igor-Ioriatti <iioriatti@gmail.com>
/bin/sh -c curl -fSL "https://ftp.drupal.org/files/projects/drupal-${DRUPAL_VERSION}.tar.gz" -o drupal.tar.gz && echo "${DRUPAL_MD5} *drupal.tar.gz" | md5sum -c - && tar -xz --strip-components=1 -f drupal.tar.gz && rm drupal.tar.gz && chown -R www-data:www-data sites modules themes
/bin/sh -c #(nop) ENV DRUPAL_MD5=57526a827771ea8a06db1792f1602a85
/bin/sh -c #(nop) ENV DRUPAL_VERSION=8.2.6
/bin/sh -c #(nop) WORKDIR /var/www/html
/bin/sh -c { echo 'opcache.memory_consumption=128'; echo 'opcache.interned_strings_buffer=8'; echo 'opcache.max_accelerated_files=4000'; echo 'opcache.revalidate_freq=60'; echo 'opcache.fast_shutdown=1'; echo 'opcache.enable_cli=1'; } > /usr/local/etc/php/conf.d/opcache-recommended.ini
/bin/sh -c apt-get update && apt-get install -y libpng12-dev libjpeg-dev libpq-dev && rm -rf /var/lib/apt/lists/* && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr && docker-php-ext-install gd mbstring opcache pdo pdo_mysql pdo_pgsql zip
/bin/sh -c a2enmod rewrite
/bin/sh -c #(nop) CMD ["apache2-foreground"]
/bin/sh -c #(nop) EXPOSE 80/tcp
/bin/sh -c #(nop) WORKDIR /var/www/html
/bin/sh -c #(nop) COPY file:24613ecbb1ce6a09f683b0753da9c26a1af07547326e8a02f6eec80ad6f2774a in /usr/local/bin/
/bin/sh -c #(nop) ENTRYPOINT ["docker-php-entrypoint"]
/bin/sh -c #(nop) COPY multi:2b7e23dbf0e975ef1ec1f186511e2789ab94e8c8734ca9fa8419c893f7357d6c in /usr/local/bin/
/bin/sh -c set -xe && buildDeps=" $PHP_EXTRA_BUILD_DEPS libcurl4-openssl-dev libedit-dev libsqlite3-dev libssl-dev libxml2-dev " && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* && export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" && docker-php-source extract && cd /usr/src/php && ./configure --with-config-file-path="$PHP_INI_DIR" --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" --disable-cgi --enable-ftp --enable-mbstring --enable-mysqlnd --with-curl --with-libedit --with-openssl --with-zlib $PHP_EXTRA_CONFIGURE_ARGS && make -j "$(nproc)" && make install && { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } && make clean && docker-php-source delete && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $buildDeps
/bin/sh -c #(nop) COPY file:207c686e3fed4f71f8a7b245d8dcae9c9048d276a326d82b553c12a90af0c0ca in /usr/local/bin/
/bin/sh -c set -xe; fetchDeps=' wget '; apt-get update; apt-get install -y --no-install-recommends $fetchDeps; rm -rf /var/lib/apt/lists/*; mkdir -p /usr/src; cd /usr/src; wget -O php.tar.xz "$PHP_URL"; if [ -n "$PHP_SHA256" ]; then echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -; fi; if [ -n "$PHP_MD5" ]; then echo "$PHP_MD5 *php.tar.xz" | md5sum -c -; fi; if [ -n "$PHP_ASC_URL" ]; then wget -O php.tar.xz.asc "$PHP_ASC_URL"; export GNUPGHOME="$(mktemp -d)"; for key in $GPG_KEYS; do gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; done; gpg --batch --verify php.tar.xz.asc php.tar.xz; rm -r "$GNUPGHOME"; fi; apt-get purge -y --auto-remove $fetchDeps
/bin/sh -c #(nop) ENV PHP_SHA256=244ac39bc657448962860aa7a590e4417f68513ad5e86ee2727b1328b0537309 PHP_MD5=6161aba9d24322d889da5d2ff944bddf
/bin/sh -c #(nop) ENV PHP_URL=https://secure.php.net/get/php-7.0.16.tar.xz/from/this/mirror PHP_ASC_URL=https://secure.php.net/get/php-7.0.16.tar.xz.asc/from/this/mirror
/bin/sh -c #(nop) ENV PHP_VERSION=7.0.16
/bin/sh -c #(nop) ENV GPG_KEYS=1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3
/bin/sh -c #(nop) ENV PHP_LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie
/bin/sh -c #(nop) ENV PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2
/bin/sh -c #(nop) ENV PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2
/bin/sh -c #(nop) ENV PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2
/bin/sh -c #(nop) ENV PHP_EXTRA_BUILD_DEPS=apache2-dev
/bin/sh -c { echo '<FilesMatch \.php$>'; echo '\tSetHandler application/x-httpd-php'; echo '</FilesMatch>'; echo; echo 'DirectoryIndex disabled'; echo 'DirectoryIndex index.php index.html'; echo; echo '<Directory /var/www/>'; echo '\tOptions -Indexes'; echo '\tAllowOverride All'; echo '</Directory>'; } | tee "$APACHE_CONFDIR/conf-available/docker-php.conf" && a2enconf docker-php
/bin/sh -c set -ex && . "$APACHE_ENVVARS" && ln -sfT /dev/stderr "$APACHE_LOG_DIR/error.log" && ln -sfT /dev/stdout "$APACHE_LOG_DIR/access.log" && ln -sfT /dev/stdout "$APACHE_LOG_DIR/other_vhosts_access.log"
/bin/sh -c a2dismod mpm_event && a2enmod mpm_prefork
/bin/sh -c set -ex && sed -ri 's/^export ([^=]+)=(.*)$/: ${\1:=\2}\nexport \1/' "$APACHE_ENVVARS" && . "$APACHE_ENVVARS" && for dir in "$APACHE_LOCK_DIR" "$APACHE_RUN_DIR" "$APACHE_LOG_DIR" /var/www/html ; do rm -rvf "$dir" && mkdir -p "$dir" && chown -R "$APACHE_RUN_USER:$APACHE_RUN_GROUP" "$dir"; done
/bin/sh -c #(nop) ENV APACHE_ENVVARS=/etc/apache2/envvars
/bin/sh -c #(nop) ENV APACHE_CONFDIR=/etc/apache2
/bin/sh -c apt-get update && apt-get install -y apache2-bin apache2.2-common --no-install-recommends && rm -rf /var/lib/apt/lists/*
/bin/sh -c mkdir -p $PHP_INI_DIR/conf.d
/bin/sh -c #(nop) ENV PHP_INI_DIR=/usr/local/etc/php
/bin/sh -c apt-get update && apt-get install -y $PHPIZE_DEPS ca-certificates curl libedit2 libsqlite3-0 libxml2 xz-utils --no-install-recommends && rm -r /var/lib/apt/lists/*
/bin/sh -c #(nop) ENV PHPIZE_DEPS=autoconf file g++ gcc libc-dev make pkg-config re2c
/bin/sh -c #(nop) CMD ["/bin/bash"]
/bin/sh -c #(nop) ADD file:89ecb642d662ee7edbb868340551106d51336c7e589fdaca4111725ec64da957 in /